config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'    
  get "students/process_report_params"
  
  resources :schools do 
    resources :standards
    resources :students do 
      collection do 
        post "mark_attendance"
        post "generate_report"
      end
    end
    member do
      get 'manage_school'      
    end  
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  belongs_to :standard
  has_many :attendance_records
  validates_length_of :name, :within => 1..20
  validates_presence_of :name
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_school, only: [:new, :edit, :show,:create,:update,:destroy,:mark_attendance,:generate_report]
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = @school.students.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = @school.students.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to manage_school_school_path(@school), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to manage_school_school_path(@school), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def mark_attendance
    date = params[:date]
    attendance_status = { "Present"=>"P", "Absent"=>"A", "Weekoff"=>"W", "Holiday"=>"H" }
    @student = @school.students.find(params[:student_id])
    @standard = @school.standards.find(params[:standard_id])
    @attendance_record = @student.attendance_records.where(month_start_date: params[:date].to_date.at_beginning_of_month).last

    if @attendance_record
      @attendance_record.attendance_hash["#{date.to_date}"] = attendance_status["#{params[:status]}"]
      @attendance_record.save
    else
      first_date = date.to_date.at_beginning_of_month
      last_date = date.to_date.at_beginning_of_month.end_of_month
      array_of_date = (first_date..last_date) 
      attendance_hash = {}
      array_of_date.map{|s| attendance_hash[s.to_s] = ""}
      @attendance_record = @student.attendance_records.new(month_start_date: date.to_date.at_beginning_of_month, standard_id: @student.standard_id, attendance_hash: attendance_hash)
      @attendance_record.save(:validate=>false)
      if @attendance_record
        @attendance_record.attendance_hash["#{date.to_date}"] = attendance_status["#{params[:status]}"]
        @attendance_record.save
      end
    end
    redirect_to manage_school_school_path(@school), notice: 'Attendance has marked.'
  end

  def generate_report
    @attendance_hash = { "P"=>"Present", "A"=>"Absent", "W"=>"Weekoff", "H"=>"Holiday" }
    @student = @school.students.find(params[:student_id])
    @standard = @school.standards.find(params[:standard_id])
    month = params[:from_month]
    year = params[:from_year]
    get_date = "1-#{month}-#{year}".to_date
    @attendance_record = @student.attendance_records.where(month_start_date: get_date).last
    @attendance_record.present? ? (@is_attendance_record = true) : (@is_attendance_record = false) 
    respond_to do |format|
      format.js
    end
  end

  def process_report_params
    @students = []
    if params[:type].present?
      @standard = Standard.find(params[:type])
      @students = @standard.students
    end  
    respond_to do |format|
      format.html
      format.json { render :json => { :type_data => @students } }
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to manage_school_school_path(@school), notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_school
      @school = School.find(params[:school_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :standard_id, :school_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
	def defaulers(attendance_hash,student)
	  @highest_wf_words = []	
	  absent_count = attendance_hash.select {|k, v| v == "A"}.keys.each {|k| @highest_wf_words << [k]}.count
      present_count = attendance_hash.select {|k, v| v == "P"}.keys.each {|k| @highest_wf_words << [k]}.count
      weekoff_count = attendance_hash.select {|k, v| v == "W"}.keys.each {|k| @highest_wf_words << [k]}.count
      holiday_count = attendance_hash.select {|k, v| v == "H"}.keys.each {|k| @highest_wf_words << [k]}.count
      total_day = attendance_hash.count
      countable_days = total_day - ( weekoff_count + holiday_count )
      percentage_weight = ( present_count * 100 ) / ( countable_days )
      standard = student.standard
      percentage_weight >= standard.min_attendance_mark ? {defaulter: "No", weightage: percentage_weight} : {defaulter: "Yes", weightage: percentage_weight}  

	end	
end

app/views/students/_form.html.erb
<%= form_for([@school,@student]) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :standard_id %><br>
    <%= f.select :standard_id, @school.standards.map{|u| [u.class_name,u.id]}, {}, :class=>"form-control" %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_generate_report.html.erb
<% if @is_attendance_record %>
  <% default = defaulers(@attendance_record.attendance_hash,@student) %>
  <h1><%=  @student.name %></h1>
  <h1>Defauler: <%= default[:defaulter] %></h1>
  <h1>Attendance Mark: <%= default[:weightage] %>%</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Standard</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @attendance_record.attendance_hash.each do |k,v| %>
        <tr>
          <td><%= k %></td>
          <td><%= v.present? ? @attendance_hash["#{v.first}"] : "No Attendance Mark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1><%=  @student.name %></h1>
  <p style="text-align: center;"><h3>There are no attendance records present.</h3></p>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_school_school_path(@school) %>

app/views/students/generate_report.js.erb
$("#attendance_report_form #add_report").empty();
$("#attendance_report_form #add_report").html("<%= j render 'generate_report' %>");

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Standard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.standard_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', school_students_path(@school) %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @student.standard_id %>
</p>

<%= link_to 'Edit', edit_school_student_path(@school,@student) %> |
<%= link_to 'Back', manage_school_school_path(@school) %>