config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'    
  get "students/process_report_params"
  
  resources :schools do 
    resources :standards
    resources :students do 
      collection do 
        post "mark_attendance"
        post "generate_report"
      end
    end
    member do
      get 'manage_school'      
    end  
  end

end

app/models/school.rb
class School < ActiveRecord::Base
  
  has_many :standards, dependent: :destroy
  has_many :students, dependent: :destroy  
  
  validates_length_of :name, :within => 1..50
  validates_uniqueness_of :name, :message => "already exists"
  validates_presence_of :name

  Day_Status = ["Working","Weekoff","Holiday"]

  def create_attendance_records
  	today_date = Date.today
  	if today_date.at_beginning_of_month == today_date
  	  first_date = Date.today.at_beginning_of_month
	    last_date = Date.today.at_beginning_of_month.end_of_month
	    array_of_date = (first_date..last_date)	
	    attendance_hash = {}
      array_of_date.map{|s| attendance_hash[s.to_s] = ""}
  	  School.find_each(batch_size: 10) do |school|
  	  	students = get_all_students(school)
  	  	students.find_each(batch_size: 10) do |student|
  	  	  attendance_records = student.attendance_records.new(month_start_date: today_date, standard_id: student.standard_id, attendance_hash: attendance_hash)
  	  	  attendance_records.save(:validate=>false)
  	  	end
  	  end  	
  	end
  end

  def self.get_defaulters
  	today_date = Date.today
  	if today_date.at_beginning_of_month == today_date
  	  last_month_date = today_date.last_month.at_beginning_of_month
  	  School.find_each(batch_size: 10) do |school|
  	  	next if school.students.empty? && school.standards.empty?
  	  	students = get_all_students(school)
  	  	students.find_each(batch_size: 10) do |student|
  	  	  last_month_att_record = student.attendance_records.where(date: last_month_date).last
  	  	  next if last_month_att_record.empty?
          attendance_hash = last_month_att_record.attendance_hash 
          @highest_wf_words = []
          absent_count = attendance_hash.select {|k, v| v == "A"}.keys.each {|k| @highest_wf_words << [k]}.count
          present_count = attendance_hash.select {|k, v| v == "P"}.keys.each {|k| @highest_wf_words << [k]}.count
          weekoff_count = attendance_hash.select {|k, v| v == "W"}.keys.each {|k| @highest_wf_words << [k]}.count
          holiday_count = attendance_hash.select {|k, v| v == "H"}.keys.each {|k| @highest_wf_words << [k]}.count
          total_day = attendance_hash.count
          countable_days = total_day - ( weekoff_count + holiday_count )
          percentage_weight = ( present_count * 100 ) / ( countable_days )
          standard = student.standard
          percentage_weight >= standard.min_attendance_mark ? last_month_att_record.update(defaulter: "No", weightage: percentage_weight) : last_month_att_record.update(defaulter: "Yes", weightage: percentage_weight)  
  	  	end
  	  end
  	end
  end

  def get_all_students(school)
  	school.students
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy,:manage_school]
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def manage_school
    @students = @school.students
    @standards = @school.standards
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :location)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name  %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Save", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.location %></td>
        <td><%= link_to 'Edit', edit_school_path(school), :class =>"btn btn-success" %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-success" %></td>
        <td><%= link_to 'Manage School', manage_school_school_path(school), :class =>"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path, :class =>"btn btn-success" %>

app/views/schools/manage_school.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Standard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.standard.class_name %></td>
        <td><%= link_to 'Edit', edit_school_student_path(@school,student), :class =>"btn btn-success" %></td>
        <td><%= link_to 'Destroy', ([@school,student]), method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_school_student_path(@school), :class =>"btn btn-success" %>


<h1>Listing Standards</h1>

<table class="table">>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Min attendance mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standards.each do |standard| %>
      <tr>
        <td><%= standard.class_name %></td>
        <td><%= standard.min_attendance_mark %></td>
        <td><%= link_to 'Edit', edit_school_standard_path(@school,standard), :class =>"btn btn-success" %></td>
        <td><%= link_to 'Destroy', ([@school,standard]), method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standard', new_school_standard_path(@school), :class =>"btn btn-success" %>



<h1>Mark Attendance</h1>

<%= form_tag mark_attendance_school_students_path(@school), :class=>"form-inline" ,:role=>"form", method: 'POST', :id=>"mark_attendance_form" do %>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputEmail2">Standard</label>
    </div>
    <div class="col-md-4">
      <div class="input-group" style="width: 100%;">
        <%= select_tag "standard_id", options_from_collection_for_select(@school.standards, "id", "class_name"),:prompt => "Select a Class", :class=>"form-control", :required => true, :style => "width:100%" %>
      </div>
      </br>
    </div>
  </div>  
  <br/>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputEmail2">Student</label>
    </div>
    <div class="col-md-4">
      <div class="input-group" style="width: 100%;">
        <%= select_tag "student_id", options_from_collection_for_select(@school.students, "id", "name"), :class=>"form-control", :required => true, :style => "width:100%"  %>    
      </div>
      </br>
    </div>
  </div>  
  <br/>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputEmail2">Date</label>
    </div>
    <div class="col-md-4">
      <%= date_field_tag "date", "" , :class=>"form-control modelname_due_date", :placeholder=> "Date", 'data-behaviour' => 'datepicker' %>   
    </div>
    </br>    
  </div>
  <br/>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputName2" style="">Status</label>
    </div>
    <div class="col-md-4">
      <div class="input-group" style="width: 100%;">
        <%= select_tag "status", "<option>Present</option><option>Absent</option><option>Weekoff</option><option>Holiday</option>".html_safe, :class=>"form-control"  %>
      </div>
      </br>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-12" style="">
      </br>
      <button type="submit" class="btn btn-info btn-trans btn-sm" style="" id = "validate_fields" ><i class='fa fa-filter'></i>Mark</button>
    </div>
  </div>
<% end %>
<br/><br/>


<h1>Generate Report</h1>

<%= form_tag generate_report_school_students_path(@school), :remote => true, :class=>"form-inline" ,:role=>"form", method: 'POST', :id=>"attendance_report_form" do %>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputEmail2">Standard</label>
    </div>
    <div class="col-md-4">
      <div class="input-group" style="width: 100%;">
        <%= select_tag "standard_id", options_from_collection_for_select(@school.standards, "id", "class_name"),:prompt => "Select a Class", :class=>"form-control", :required => true, :style => "width:100%" %>
      </div>
      </br>
    </div>
  </div>  
  <br/>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputEmail2">Student</label>
    </div>
    <div class="col-md-4">
      <div class="input-group" style="width: 100%;">
        <%= select_tag "student_id", options_from_collection_for_select(@school.students, "id", "name"), :class=>"form-control", :required => true, :style => "width:100%"  %>    
      </div>
      </br>
    </div>
  </div>  
  <br/>
  <div class="row">
    <div class="col-md-3">
      <label for="exampleInputEmail2">Month</label>
    </div>
    <div class="col-md-4">
      <div>
        <%= select_month(Date.today, {}, {:class => 'form-control',:name => "from_month"}) %>
        <%= select_year(Date.today,  {:start_year => Date.today.year, :end_year => Date.today.year-3}, {:class => 'form-control',:name => "from_year"}) %>
        </br>
      </div>
    </div>      
  </div>

  <div class="row">
    <div class="col-md-12" style="">
      </br>
      <button type="submit" class="btn btn-info btn-trans btn-sm" style="" id = "validate_field" ><i class='fa fa-filter'></i>Mark</button>
    </div>
  </div>

  <div id="add_report"></div>
<% end %>
<br/><br/>


<script type="text/javascript">

  $("#attendance_report_form #standard_id").change(function(){
    var type_val = $("#attendance_report_form #standard_id").val();
    $.ajax({
      type: "GET",
      url: '/students/process_report_params',
      dataType: "JSON",
      data: {type: type_val},
      success:function(data) {      
        $('#attendance_report_form #student_id').empty();   
        console.log(data.type_data);   
        jQuery.each(data.type_data,function(i, v) {
             $('#attendance_report_form #student_id').append( $('<option value="'+data.type_data[i]["id"] +'">'+data.type_data[i]["name"] +'</option>'));
           });
      }
    });
  });

  $("#mark_attendance_form #standard_id").change(function(){
    var type_val = $("#mark_attendance_form #standard_id").val();
    $.ajax({
      type: "GET",
      url: '/students/process_report_params',
      dataType: "JSON",
      data: {type: type_val},
      success:function(data) {      
        $('#mark_attendance_form #student_id').empty();   
        console.log(data.type_data);   
        jQuery.each(data.type_data,function(i, v) {
             $('#mark_attendance_form #student_id').append( $('<option value="'+data.type_data[i]["id"] +'">'+data.type_data[i]["name"] +'</option>'));
           });
      }
    });
  });

 </script>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @school.location %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>