config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'    
  get "students/process_report_params"
  
  resources :schools do 
    resources :standards
    resources :students do 
      collection do 
        post "mark_attendance"
        post "generate_report"
      end
    end
    member do
      get 'manage_school'      
    end  
  end

end

app/models/standard.rb
class Standard < ActiveRecord::Base
  has_many :students, dependent: :destroy  
end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  before_action :set_standard, only: [:show, :edit, :update, :destroy]
  before_action :set_school, only: [:new, :edit, :show,:create,:update,:destroy]

  # GET /standards
  # GET /standards.json
  def index
    @standards = Standard.all
  end

  # GET /standards/1
  # GET /standards/1.json
  def show
  end

  # GET /standards/new
  def new
    @standard = @school.standards.build
  end

  # GET /standards/1/edit
  def edit
  end

  # POST /standards
  # POST /standards.json
  def create
    @standard = @school.standards.new(standard_params)

    respond_to do |format|
      if @standard.save
        format.html { redirect_to manage_school_school_path(@school), notice: 'Standard was successfully created.' }
        format.json { render :show, status: :created, location: @standard }
      else
        format.html { render :new }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standards/1
  # PATCH/PUT /standards/1.json
  def update
    respond_to do |format|
      if @standard.update(standard_params)
        format.html { redirect_to manage_school_school_path(@school), notice: 'Standard was successfully updated.' }
        format.json { render :show, status: :ok, location: @standard }
      else
        format.html { render :edit }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standards/1
  # DELETE /standards/1.json
  def destroy
    @standard.destroy
    respond_to do |format|
      format.html { redirect_to manage_school_school_path(@school), notice: 'Standard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standard
      @standard = Standard.find(params[:id])
    end

    def set_school
      @school = School.find(params[:school_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standard_params
      params.require(:standard).permit(:school_id, :class_name, :min_attendance_mark,:school_id)
    end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/views/standards/_form.html.erb
<%= form_for([@school,@standard]) do |f| %>
  <% if @standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standard.errors.count, "error") %> prohibited this standard from being saved:</h2>

      <ul>
      <% @standard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :min_attendance_mark %><br>
    <%= f.text_field :min_attendance_mark, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standards/edit.html.erb
<h1>Editing Standard</h1>

<%= render 'form' %>

<%= link_to 'Back', manage_school_school_path(@school) %>

app/views/standards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Standards</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Class name</th>
      <th>Min attendance mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standards.each do |standard| %>
      <tr>
        <td><%= standard.school_id %></td>
        <td><%= standard.class_name %></td>
        <td><%= standard.min_attendance_mark %></td>
        <td><%= link_to 'Show', standard %></td>
        <td><%= link_to 'Edit', edit_standard_path(standard) %></td>
        <td><%= link_to 'Destroy', standard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standard', new_standard_path %>

app/views/standards/new.html.erb
<h1>New Standard</h1>

<%= render 'form' %>

<%= link_to 'Back', school_standards_path(@school) %>

app/views/standards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @standard.school_id %>
</p>

<p>
  <strong>Class name:</strong>
  <%= @standard.class_name %>
</p>

<p>
  <strong>Min attendance mark:</strong>
  <%= @standard.min_attendance_mark %>
</p>

<%= link_to 'Edit', edit_school_standard_path(@school,@standard) %> |
<%= link_to 'Back', manage_school_school_path(@school) %>